export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_SUCCESSFUL = 'GET_COUNTRIES_SUCCESSFUL';
export const GET_COUNTRIES_FAILED = 'GET_COUNTRIES_FAILED';

export const GET_CITIES = 'GET_CITIES';
export const GET_CITIES_SUCCESSFUL = 'GET_CITIES_SUCCESSFUL';
export const GET_CITIES_FAILED = 'GET_CITIES_FAILED';